# Rustfmt configuration

edition = "2024"
hard_tabs = false
tab_spaces = 4
max_width = 80
newline_style = "Auto"
use_small_heuristics = "Default"
reorder_imports = true
reorder_modules = true
remove_nested_parens = true
